name: MAUDE
favicon: null
layout_spectrum: 0.6400318860542029
typography_spectrum: 0.61744
title: MAUDE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#a39f9c'
    - '#1c1b19'
    - '#d4d0cf'
    - '#4c4744'
  brandStrength: 0.058183074463158846
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.24932186864316463
purpose: []
