name: MAUDE
favicon: null
layout_spectrum: 0.6400318860542029
typography_spectrum: 0.8627853412181139
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.058183074463158846
  lightness: 0.25455373781733215
  saturation: 0.5005764917004853
  rhythmicContrast: 0.24932186864316463
purpose: []
